"""update talleres fields

Revision ID: 516c71a3b634
Revises: 069ce713468a
Create Date: 2026-04-19 03:21:34.020889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516c71a3b634'
down_revision: Union[str, Sequence[str], None] = '069ce713468a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talleres', sa.Column('ubicacion', sa.String(length=255), nullable=False))
    op.add_column('talleres', sa.Column('email', sa.String(length=254), nullable=False))
    op.alter_column('talleres', 'direccion',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('talleres', 'telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('talleres', 'telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('talleres', 'direccion',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('talleres', 'email')
    op.drop_column('talleres', 'ubicacion')
    # ### end Alembic commands ###
